apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  selector:
    app: traefik
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 80
      nodePort: 31080
    - protocol: TCP
      name: admin
      port: 8080
      targetPort: 8080
      nodePort: 31081
  type: NodePort
