apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order-generation
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: order-generation
                port:
                  number: 8000