apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      initContainers:
        - name: wait-for-elasticsearch
          image: busybox:1.36
          command:
            [
              "sh",
              "-c",
              "until wget -O- http://elasticsearch:9200; do echo waiting for elasticsearch; sleep 2; done;",
            ]
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.10.2
          env:
            - name: ELASTICSEARCH_URL
              value: "http://elasticsearch:9200"
          ports:
            - containerPort: 5601
          livenessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 120
            periodSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
