apiVersion: apps/v1
kind: Deployment
metadata:
  name: failed-order-handler
spec:
  selector:
    matchLabels:
      app: failed-order-handler
  template:
    metadata:
      labels:
        app: failed-order-handler
    spec:
      initContainers:
        - name: init-wait-for-rabbitmq
          image: spyker77/eda-failed_order_handler:latest
          command: ["/wait-for-it.sh", "rabbitmq:5672", "--timeout=60"]
      containers:
        - name: failed-order-handler
          image: spyker77/eda-failed_order_handler:latest
          env:
            - name: RABBITMQ_URL
              value: "amqp://admin:admin@rabbitmq/"
            - name: REDIS_URL
              value: "redis://redis:6379"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250"
